DROP INDEX IDX_Accounts_FNAME ON Accounts;
DROP INDEX IDX_Accounts_REV_FNAME ON Accounts;

ALTER TABLE Accounts
DROP COLUMN FNAME;
ALTER TABLE Accounts
DROP COLUMN REV_FNAME;

ALTER TABLE Accounts
ADD FNAME AS LTRIM(RTRIM(
    CONCAT_WS(' ',
        NULLIF(LTRIM(RTRIM(FIRST)), ''),
        NULLIF(LTRIM(RTRIM(MIDDLE)), ''),
        NULLIF(LTRIM(RTRIM(LAST)), '')
    )
));
ALTER TABLE Accounts
ADD REV_FNAME AS LTRIM(RTRIM(
    CONCAT_WS(' ',
		NULLIF(LTRIM(RTRIM(LAST)), ''),
        NULLIF(LTRIM(RTRIM(MIDDLE)), ''),
        NULLIF(LTRIM(RTRIM(FIRST)), '')
    )
));

CREATE INDEX IDX_Accounts_FNAME ON Accounts(FNAME);
CREATE INDEX IDX_Accounts_REV_FNAME ON Accounts(REV_FNAME);

INSERT INTO DbVersion (Version) VALUES (4);