ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_CUSTNOTE DEFAULT ('') FOR CUSTNOTE;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_SPOUSE DEFAULT ('') FOR SPOUSE;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_CARE_OF DEFAULT ('') FOR CARE_OF;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_EMAIL DEFAULT ('') FOR EMAIL;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_C_PHONE DEFAULT ('') FOR C_PHONE;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_H_PHONE DEFAULT ('') FOR H_PHONE;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_W_PHONE DEFAULT ('') FOR W_PHONE;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_ADD_DATE DEFAULT ('') FOR ADD_DATE;
ALTER TABLE Accounts
ADD CONSTRAINT DF_Accounts_MIDDLE DEFAULT ('') FOR MIDDLE;

ALTER TABLE ServiceLocs
ADD CONSTRAINT DF_ServiceLocs_SUFFIX DEFAULT ('') FOR SUFFIX;
ALTER TABLE ServiceLocs
ADD CONSTRAINT DF_ServiceLocs_SERV_NOTES DEFAULT ('') FOR SERV_NOTES;
ALTER TABLE ServiceLocs
ADD CONSTRAINT DF_ServiceLocs_ADD_DATE DEFAULT ('') FOR ADD_DATE;
ALTER TABLE ServiceLocs
ADD CONSTRAINT DF_ServiceLocs_CATEGORY DEFAULT ('UNASSIGNED') FOR CATEGORY;

ALTER TABLE Utilities
DROP CONSTRAINT DF_Utilities_APPLY_HOW;
ALTER TABLE Utilities
DROP CONSTRAINT DF_Utilities_MAKE;
ALTER TABLE Utilities
DROP CONSTRAINT DF_Utilities_BILL_CODE;

ALTER TABLE Utilities
DROP COLUMN APPLY_HOW;
ALTER TABLE Utilities
DROP COLUMN MAKE;
ALTER TABLE Utilities
DROP COLUMN BILL_CODE;

ALTER TABLE ArchivedUtilities
DROP COLUMN APPLY_HOW;
ALTER TABLE ArchivedUtilities
DROP COLUMN MAKE;
ALTER TABLE ArchivedUtilities
DROP COLUMN BILL_CODE;