use mdms_prod;

ALTER TABLE Usages
ADD USAGE_PK INT IDENTITY(1,1) NOT NULL;

ALTER TABLE Usages
ADD CONSTRAINT PK_Usages PRIMARY KEY (USAGE_PK);

ALTER TABLE Transactions
ADD TRANS_PK INT IDENTITY(1,1) NOT NULL;

ALTER TABLE Transactions
ADD CONSTRAINT PK_Transactions PRIMARY KEY (TRANS_PK);