use mdms_prod;

INSERT INTO Notes (CREATE_FOR, [TEXT], [USER])
SELECT
    CAST(s.SERV_ID AS VARCHAR(50)) AS CREATE_FOR,
    LTRIM(RTRIM(s.SERV_NOTES)) AS [TEXT],
    SUSER_SNAME() AS [USER]
FROM dbo.ServiceLocs s
WHERE
    s.SERV_NOTES IS NOT NULL
    AND LTRIM(RTRIM(s.SERV_NOTES)) <> '';

--remove old columns
ALTER TABLE ServiceLocs
DROP CONSTRAINT DF_ServiceLocs_SERV_NOTES;

ALTER TABLE ServiceLocs
DROP COLUMN SERV_NOTES;

ALTER TABLE ArchivedServiceLocs
DROP COLUMN SERV_NOTES;
