UPDATE ArchivedAccounts
SET BILL_ADDR = ''
WHERE BILL_ADDR IS NULL;

ALTER TABLE ArchivedAccounts
ALTER COLUMN BILL_ADDR VARCHAR(257) NOT NULL;

ALTER TABLE ArchivedAccounts
ALTER COLUMN FNAME VARCHAR(152) NULL;

ALTER TABLE ArchivedAccounts
ALTER COLUMN REV_FNAME VARCHAR(152) NULL;

ALTER TABLE ArchivedServiceLocs
DROP COLUMN SERV_STAT;

UPDATE Utilities
SET READ_SEQ = LTRIM(STR(CONVERT(INT, READ_SEQ)))
WHERE ISNUMERIC(READ_SEQ) = 1 AND READ_SEQ <> '';

ALTER TABLE Utilities
ALTER COLUMN READ_SEQ VARCHAR(5) NOT NULL;

ALTER TABLE ArchivedUtilities
ALTER COLUMN READ_SEQ VARCHAR(5) NOT NULL;

INSERT INTO DbVersion (Version) VALUES (2);