CREATE TABLE GroupBills (
    ACCT_NO        VARCHAR(50) NOT NULL,
    FNAME          VARCHAR(152) NOT NULL,
    UTILITY        VARCHAR(1) NOT NULL,
    AMOUNT         VARCHAR(10) NOT NULL,
    NUMBER         VARCHAR(50) NOT NULL,
    STREET         VARCHAR(50) NOT NULL,
    SUFFIX         VARCHAR(50) NOT NULL,
    BALANCE        VARCHAR(10) NULL,
    PREV_BALANCE   VARCHAR(10) NULL,
    CHARGE         VARCHAR(10) NOT NULL,
    DIFF           VARCHAR(10) NOT NULL,
    POST_DATE      VARCHAR(10) NOT NULL,
    DUE_DATE       VARCHAR(10) NOT NULL,
    BILL_TO        VARCHAR(257) NOT NULL,
    UTIL_NAME      VARCHAR(50) NOT NULL,
    MESSAGE        VARCHAR(101) NULL
);

INSERT INTO DbVersion (Version) VALUES (3);