ALTER TABLE Rates DROP CONSTRAINT DF_Rates_ALLOWANCE;
ALTER TABLE Rates DROP COLUMN IF EXISTS ALLOWANCE;
ALTER TABLE RateDescs DROP COLUMN IF EXISTS PEN_CODE;
ALTER TABLE RateDescs DROP COLUMN IF EXISTS USGUTIL;
ALTER TABLE RateDescs ADD ASSOC varchar(1) NOT NULL DEFAULT '';