use [mdms_prod];

ALTER TABLE Accounts
ADD KEEP_BILLING BIT NOT NULL 
    CONSTRAINT DF_Accounts_KEEP_BILLING DEFAULT (1);
ALTER TABLE Accounts
ADD BILL_EMAIL BIT NOT NULL 
    CONSTRAINT DF_Accounts_BILL_EMAIL DEFAULT (0);
ALTER TABLE Accounts
ADD BILL_PAPER BIT NOT NULL 
    CONSTRAINT DF_Accounts_BILL_PAPER DEFAULT (1);

ALTER TABLE ArchivedAccounts
ADD KEEP_BILLING BIT NOT NULL 
    CONSTRAINT DF_ArchivedAccounts_KEEP_BILLING DEFAULT (1);
ALTER TABLE ArchivedAccounts
ADD BILL_EMAIL BIT NOT NULL 
    CONSTRAINT DF_ArchivedAccounts_BILL_EMAIL DEFAULT (0);
ALTER TABLE ArchivedAccounts
ADD BILL_PAPER BIT NOT NULL 
    CONSTRAINT DF_ArchivedAccounts_Accounts_BILL_PAPER DEFAULT (1);