use mdms_prod;

UPDATE Transactions SET
DUE_DATE = DATEADD(DAY, 24, POST_DATE),
TRAN_DATE = POST_DATE
WHERE DUE_DATE IS NULL;

ALTER TABLE Transactions
ALTER COLUMN DUE_DATE DATE NOT NULL;

ALTER TABLE Transactions
ALTER COLUMN TRAN_DATE DATE NOT NULL;
