use mdms_prod;

CREATE TABLE PendingItems
(
    ITEM_PK INT IDENTITY(1,1) NOT NULL,
    ACCT_NO VARCHAR(50) NOT NULL,
    UTILITY TINYINT NOT NULL,
    QB_ITEM VARCHAR(50) NOT NULL,
    ITEM_DESC VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    TRAN_DATE DATE NOT NULL,

    CONSTRAINT PK_PendingItems PRIMARY KEY (ITEM_PK)
);
