use mdms_prod;

CREATE TABLE UtilsConfig
(
    CODE TINYINT NOT NULL,
    DISPLAY VARCHAR(50) NOT NULL,
    QB_ITEM_NAME VARCHAR(50) NOT NULL,
    QB_ITEM_ID VARCHAR(50) NOT NULL,
    ALIAS VARCHAR(50) NOT NULL
);
